apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nar-deploy
  name: nar-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nar-deploy
  template:
    metadata:
      labels:
        app: nar-deploy
    spec:
      containers:
      - image: nar24/takin:6
        name: pet
